export About from './About/About';
export App from './App/App';
export About from './About/About';
export Contact from './Contact/Contact';
export Home from './Home/Home';
export PrivacyPolicy from './PrivacyPolicy/PrivacyPolicy';
// export Widgets from './Widgets/Widgets';
// export Login from './Login/Login';
// export LoginSuccess from './LoginSuccess/LoginSuccess';
// export Survey from './Survey/Survey';
// export Chat from './Chat/Chat';
export NotFound from './NotFound/NotFound';
