version: '2'

services:
  main:
    build: .
    image: sauravskumar/atmed_index
    container_name: atmed_index
    command: bash -c "API_HOST=192.168.43.216 HOST=192.168.43.216 npm run dev"
    ports:
      - 3000:3000
      - 3001:3001
      - 3030:3030
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./static/files:/usr/src/app/static/files
    environment:
        NODE_ENV: development